### Numpy Library 

In [ ]:
import numpy as np
 

In [ ]:
# 1D Array
array1=np.array([1,2,3,4,5])
print(array1,type(array1))
print(len(array1))


# 2D Array 
AA=np.array([[1,2,3,4],[5,6,7,8]])
print(AA,type(AA))
print(AA.shape)


# 3D Array
Array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"{Array}\n{type(Array)}\n{Array.shape}")



In [ ]:
np.arange(0,20,2).reshape(5,2)
# some inbuilt functions 
np.array([1,2,3]) # creates Array 
np.zeros((2,3))  # creats a Array with 2 rows and 3 column all are zeros 
np.ones((3,3)) # creates a matrices 3x3 all elements are 1
np.empty((2,2))  # creates a Empty Array 
np.arange(0,10,2) # creates a 1D Array by default 
np.linspace(0,1,5) # creates a Array all Elements have same diff with their Sucessor
np.eye(3)  # identity matrics 3x3 
np.random.rand(3,3) # this creats a 3D Array that has random float values between 0-1 
np.random.randint(1,10,(2,2)) #this Creats a 2x2 matrics having random elements between 1-9



In [ ]:
# to master this numpy operations 
import numpy as np   # Import NumPy library

# ==============================
# 1️⃣ Array Creation
# ==============================

a = np.array([1, 2, 3])        # Create 1D array from list
b = np.zeros((2, 3))           # Create 2x3 array filled with 0
c = np.ones((2, 2))            # Create 2x2 array filled with 1
d = np.empty((2, 2))           # Create 2x2 array with random memory values (not initialized)
e = np.arange(0, 10, 2)        # Create array from 0 to 9 with step 2 → [0,2,4,6,8]
f = np.linspace(0, 1, 5)       # Create 5 evenly spaced numbers between 0 and 1
g = np.random.rand(3, 3)       # Create 3x3 array with random float values (0 to 1)
h = np.random.randint(1, 10, (2, 2))  # Create 2x2 array with random integers from 1 to 9


# ==============================
# 2️⃣ Important Attributes
# ==============================

arr = np.array([[1, 2, 3], [4, 5, 6]])  # Create 2D array (2 rows, 3 columns)

print(arr.shape)   # Returns shape of array → (rows, columns) → (2,3)
print(arr.ndim)    # Returns number of dimensions → 2
print(arr.size)    # Returns total number of elements → 6
print(arr.dtype)   # Returns data type of elements (int64, float64, etc.)
print(arr.T)       # Transpose → Converts rows into columns


# ==============================
# 3️⃣ Mathematical Operations
# ==============================

print(np.sum(arr))     # Sum of all elements → 21
print(np.mean(arr))    # Average of all elements
print(np.median(arr))  # Middle value after sorting
print(np.std(arr))     # Standard deviation (spread of data)
print(np.min(arr))     # Minimum value
print(np.max(arr))     # Maximum value
print(np.sqrt(arr))    # Square root of each element
print(np.exp(arr))     # e^x (exponential) of each element
print(np.log(arr))     # Natural log (ln) of each element


# ==============================
# 4️⃣ Axis Operations
# ==============================

print(arr.sum(axis=0))  # Column-wise sum → Adds vertically
print(arr.sum(axis=1))  # Row-wise sum → Adds horizontally


# ==============================
# 5️⃣ Reshaping
# ==============================

reshaped = arr.reshape(3, 2)   # Change shape from (2,3) to (3,2)
flattened = arr.ravel()        # Flatten array into 1D (returns view)
flat_copy = arr.flatten()      # Flatten array into 1D (returns copy)


# ==============================
# 6️⃣ Indexing & Filtering
# ==============================

print(arr[0])          # Access first row → [1,2,3]
print(arr[:, 1])       # Access second column
print(arr[arr > 3])    # Return elements greater than 3


# ==============================
# 7️⃣ Sorting & Searching
# ==============================

print(np.sort(arr))        # Sort elements row-wise
print(np.argsort(arr))     # Return indices of sorted elements
print(np.where(arr > 3))   # Return indices where condition is True
print(np.unique(arr))      # Return unique elements (remove duplicates)


# ==============================
# 8️⃣ Matrix Operations
# ==============================

A = np.array([[1, 2], [3, 4]])   # Define matrix A
B = np.array([[5, 6], [7, 8]])   # Define matrix B

print(np.dot(A, B))          # Matrix multiplication using dot()
print(A @ B)                 # Matrix multiplication using @ operator
print(np.linalg.inv(A))      # Inverse of matrix A
print(np.linalg.det(A))      # Determinant of matrix A


In [ ]:
# Numpy Vectorized Operation 
Array1=np.array([1,2,3,4,5])
Array2=np.array([10,20,30,40,50])

# Element wise operations 
# Addition 
print("Addition :",Array1+Array2)

# Substraction 
print("Substraction :",Array1-Array2)

# Multiplication 
print("Multiplication:",Array1*Array2)

#Division 
print("Division :",Array1/Array2)



In [ ]:
# Universal function 
arr=np.array([1,2,33,4,5,7,8,9,0])
# Square root 
print(np.sqrt(arr))

# Exponential 
print(np.exp(arr))

# sine 
print(np.sin(arr))
try:
    # natural log 
    print(np.log(arr))
except Exception :
    print("Error")


In [ ]:
# Array slicing 

Array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# print(Array)

print(Array[1:,2:])
print(Array[0:,1:])
print(Array[2:,1:])
print(Array[0:2,2:4])


In [ ]:
print(np.eye(3))

data =np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5)&(data<=8)]


### Numpy Practice !

In [ ]:
Array_1=np.array([1,2,3,4,5,6,7,8,9])

# mean 
Mean=np.mean(Array_1)
print(Mean)

# Median 
median =np.median(Array_1)
print(median)


# standard deviation 
Standard_deviation=np.std(Array_1)
print(Standard_deviation)

# variance 
Variance = np.var(Array_1)
print(Variance)


In [ ]:
# Implementing the Numpy operation / function 
import numpy as np 

class Numpy_func:
    
    def __init__(self, Array_list):
        print("We are only operating with 3x3 matrix")
        self.A = np.array(Array_list)
        print(f"Array [A]:\n{self.A}")

    # ==============================
    # Array Creation
    # ==============================
    def Array_Creation(self):
        print("Zeros:\n", np.zeros((3,3)))
        print("Ones:\n", np.ones((3,3)))
        print("Identity:\n", np.eye(3))
        print("Empty:\n", np.empty((3,3)))
        print("Arange:\n", np.arange(0,9,1))
        print("Linspace:\n", np.linspace(0,5,5))
        print("Random:\n", np.random.rand(3,3))
        print("Random Int:\n", np.random.randint(1,10,(3,3)))

    # ==============================
    # Important Attributes
    # ==============================
    def Important_Attributes(self):
        print("Shape:", self.A.shape)
        print("Dimensions:", self.A.ndim)
        print("Datatype:", self.A.dtype)
        print("Size:", self.A.size)
        print("Transpose:\n", self.A.T)

    # ==============================
    # Mathematical Operations
    # ==============================
    def Mathematical_operations(self):
        Choice = int(input(
            "1.Sum\n2.Mean\n3.Median\n4.Standard Deviation\n"
            "5.Minimum\n6.Maximum\n7.Square Root\n"
            "8.Exponential\n9.Natural Log\nEnter your choice: "
        ))

        if Choice == 1:
            print("Sum:", np.sum(self.A))

        elif Choice == 2:
            print("Mean:", np.mean(self.A))

        elif Choice == 3:
            print("Median:", np.median(self.A))

        elif Choice == 4:
            print("Standard Deviation:", np.std(self.A))

        elif Choice == 5:
            print("Minimum:", np.min(self.A))

        elif Choice == 6:
            print("Maximum:", np.max(self.A))

        elif Choice == 7:
            print("Square Root:\n", np.sqrt(self.A))

        elif Choice == 8:
            print("Exponential:\n", np.exp(self.A))

        elif Choice == 9:
            print("Natural Log:\n", np.log(self.A))

        else:
            print("Invalid Choice!")

    # ==============================
    # Axis Operations
    # ==============================
    def Axis_Operation(self):
        print("Column-wise Sum:", self.A.sum(axis=0))
        print("Row-wise Sum:", self.A.sum(axis=1))

    # ==============================
    # Reshaping
    # ==============================
    def Reshaping(self):
        reshaped = self.A.reshape(1,9)
        print("Reshaped (1x9):\n", reshaped)

        flattened = self.A.ravel()
        print("Ravel:\n", flattened)

        flat_copy = self.A.flatten()
        print("Flatten Copy:\n", flat_copy)

    # ==============================
    # Indexing & Filtering
    # ==============================
    def Indixing_filtering(self):
        print("First Row:", self.A[0])
        print("Second Column:", self.A[:,1])
        print("Elements > 2:", self.A[self.A > 2])

    # ==============================
    # Sorting & Searching
    # ==============================
    def Sortting_Searching(self):
        print("Sorted:\n", np.sort(self.A))
        print("Argsort:\n", np.argsort(self.A))
        print("Where > 2:", np.where(self.A > 2))
        print("Unique:", np.unique(self.A))

    # ==============================
    # Matrix Operations
    # ==============================
    def Matrix_Operations(self):
        print("Enter second 3x3 matrix values row-wise:")
        B = []
        for i in range(3):
            row = list(map(int, input().split()))
            B.append(row)

        self.B = np.array(B)

        print("Dot Product:\n", np.dot(self.A, self.B))
        print("Using @ operator:\n", self.A @ self.B)

        # Inverse only if determinant ≠ 0
        if np.linalg.det(self.A) != 0:
            print("Inverse of A:\n", np.linalg.inv(self.A))
        else:
            print("Matrix A is singular, inverse not possible.")

        print("Determinant of B:", np.linalg.det(self.B))


# ==============================
# Main Program
# ==============================
object1 = Numpy_func([[1,2,3],[4,5,6],[7,8,9]])

Choice = int(input(
    "\n1.Array_Creation\n2.Important_Attributes\n"
    "3.Mathematical\n4.Axis_Operation\n5.Reshaping\n"
    "6.Indexing\n7.Sorting_Searching\n8.Matrix_Operations\n"
    "Enter Your Choice: "
))

if Choice == 1:
    object1.Array_Creation()
elif Choice == 2:
    object1.Important_Attributes()
elif Choice == 3:
    object1.Mathematical_operations()
elif Choice == 4:
    object1.Axis_Operation()
elif Choice == 5:
    object1.Reshaping()
elif Choice == 6:
    object1.Indixing_filtering()
elif Choice == 7:
    object1.Sortting_Searching()
elif Choice == 8:
    object1.Matrix_Operations()
else:
    print("Invalid Choice! Enter between 1-8.")

In [2]:
# Numpy Practice 
import numpy as np

matrix=np.zeros((10,10))
matrix


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
Id_matrix=np.eye(6,6)
Id_matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
random_integers = [
    57, 12, 89, 34, 76, 23, 91, 45, 68,
    10, 99, 54, 32, 71, 84, 27, 63, 18,
    50, 3, 95, 41, 72, 29, 60, 14, 87,
    36, 78, 21, 66, 9, 100, 48, 82, 15
]

Data=np.array(random_integers)
print(Data,type(Data))

np.shape(Data)
np.reshape(Data,(6,6))

[ 57  12  89  34  76  23  91  45  68  10  99  54  32  71  84  27  63  18
  50   3  95  41  72  29  60  14  87  36  78  21  66   9 100  48  82  15] <class 'numpy.ndarray'>


array([[ 57,  12,  89,  34,  76,  23],
       [ 91,  45,  68,  10,  99,  54],
       [ 32,  71,  84,  27,  63,  18],
       [ 50,   3,  95,  41,  72,  29],
       [ 60,  14,  87,  36,  78,  21],
       [ 66,   9, 100,  48,  82,  15]])

In [13]:
# statistical operation on numpy array
 
print(np.reshape(Data,(6,6)))


#mean
Mean=np.mean(Data)
print(f"Mean : {Mean}")

# Median 
Median = np.median(Data)
print(f"Median : {Median}")

# Standard deviation 
std_dev=np.std(Data)
print(f"Standard Deviation :{std_dev}")




[[ 57  12  89  34  76  23]
 [ 91  45  68  10  99  54]
 [ 32  71  84  27  63  18]
 [ 50   3  95  41  72  29]
 [ 60  14  87  36  78  21]
 [ 66   9 100  48  82  15]]
Mean : 51.638888888888886
Median : 52.0
Standard Deviation :29.242428058651903


In [16]:
import numpy as np 
Integers=[15, -3, 42, -17, 8, -29, 64, -1, 23, -50]
Array=np.array(Integers)

Array[Array<0]=0

print(Array)

[15  0 42  0  8  0 64  0 23  0]


In [20]:
#Extract all even numbers from an array

numbers=[x for x in range (21)]
Num=np.array(numbers)
even=[]
odd =[]

for i in Num:
    if i % 2==0 :
        print(f"{i} is a even number ")
        if i not in even:
            even.append(i)

    else:
        print(f"{i} is odd number ")
        if i not in odd :
            odd.append(i)


print(f"Even : {even}")
print(f"Odd : {odd}")


0 is a even number 
1 is odd number 
2 is a even number 
3 is odd number 
4 is a even number 
5 is odd number 
6 is a even number 
7 is odd number 
8 is a even number 
9 is odd number 
10 is a even number 
11 is odd number 
12 is a even number 
13 is odd number 
14 is a even number 
15 is odd number 
16 is a even number 
17 is odd number 
18 is a even number 
19 is odd number 
20 is a even number 
Even : [np.int64(0), np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10), np.int64(12), np.int64(14), np.int64(16), np.int64(18), np.int64(20)]
Odd : [np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9), np.int64(11), np.int64(13), np.int64(15), np.int64(17), np.int64(19)]


In [21]:
# Flatten a 3D array into 1D.

matrix=np.array([[1,2,3],[4,5,6],[6,7,8]])
Array_1D=matrix.flatten()
print(Array_1D)


[1 2 3 4 5 6 6 7 8]


In [26]:
#Compute cumulative sum of a 1D array.
num=np.array([1, 2, 3, 4 ,5, 6, 6, 7, 8])
sum=num.sum()
print(sum)

#Find unique elements and their counts


arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 1, 2])

unique_values, counts = np.unique(arr, return_counts=True)

print("Unique values:", unique_values)
print("Counts:", counts)




42
Unique values: [1 2 3 4 5]
Counts: [2 3 1 3 1]


In [ ]:
#Sort a 2D array by the second column.
import numpy as np

mat_2x2 = np.array([[1, 2, 3],
                    [2, 3, 4]])

# Get the order of indices based on second column (index 1)
sorted_mat = mat_2x2[mat_2x2[:, 1].argsort()]

print(sorted_mat)

[[1 2 3]
 [2 3 4]]


In [42]:
#Create a boolean mask for values greater than 50

lst=[x for x in range (40,80)]
RR=np.array(lst)
mask=RR>50
print(mask)


[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [45]:
#Normalize values between 0 and 1.
normal=np.arange(0,1,0.2)
print(normal)


[0.  0.2 0.4 0.6 0.8]


In [5]:
#Find indices of elements divisible by 5.
import numpy as np
data =[1,2,5,10,23,15,22,20,24,25]
Data_Array=np.array(data)

indices=np.where(Data_Array%5==0) # np.where is used to find the index of the elements 

print(indices)


(array([2, 3, 5, 7, 9]),)


In [ ]:
#Reverse a NumPy array.
